### PR TITLE
fix #21

### LINKED ISSUE #21: Use HTTP instead of TCP and Go RPC

### PR DESCRIPTION
**Pull request by hanxi**

### CODE REVIEW

**Comment by hanxi** [comment]
I delete trans-localfile feature. I will use another way to achieve this feature.

1. http static file server use ./files/ directory for upload
2. upload need trans file to lemonade server to ./files/ directory
3. open file use /open method api

**Comment by hanxi** [comment]
@mattn Any suggestions?

**Comment by mattn** [comment]
Seems good to me.  @pocke How do you think about this?

**Comment by pocke** [comment]
Looks good to me. Thank you @hanxi !

**Comment by mattn** [comment]
Thanks. This should be fixed in https://github.com/lemonade-command/lemonade/pull/39

**Pull request closed without merging**
